from django.urls import path
from .views import (
    SendOTPView, VerifyOTPView, UserProfileView, AdminMemberView, 
    CategoryListView, AdminAddPointsView, AdminAddWalkView,
    EventListView, EventRegisterAttendanceView, AdminEventsView, AdminEventAttendeesView, AdminEventCloseView,
    AdminEventLocationView, AdminImportMembersView, MemberActivityView, AdminActivityView,
    AdminPointsSettingsView, LeaderboardView,
    NewsListView, NewsDetailView, NewsCreateView, NewsLikeToggleView,
    AdminPendingNewsView, AdminReviewNewsView, PublicStatsView,
    PublicUpcomingEventsView, MonthlyCategoryChampionsView, DevLoginView, LogoutView
)

urlpatterns = [
    path('send-otp/', SendOTPView.as_view(), name='send_otp'),
    path('verify-otp/', VerifyOTPView.as_view(), name='verify_otp'),
    path('profile/', UserProfileView.as_view(), name='profile'),
    path('categories/', CategoryListView.as_view(), name='categories'),
    path('admin/members/', AdminMemberView.as_view(), name='admin_members'),
    path('admin/add-points/', AdminAddPointsView.as_view(), name='admin_add_points'),
    path('admin/add-walk/', AdminAddWalkView.as_view(), name='admin_add_walk'),
    path('events/', EventListView.as_view(), name='events_list'),
    path('events/register-attendance/', EventRegisterAttendanceView.as_view(), name='events_register_attendance'),
    path('admin/events/', AdminEventsView.as_view(), name='admin_events'),
    path('admin/event-attendees/', AdminEventAttendeesView.as_view(), name='admin_event_attendees'),
    path('admin/events/close/', AdminEventCloseView.as_view(), name='admin_events_close'),
    path('admin/event-locations/', AdminEventLocationView.as_view(), name='admin_event_locations'),
    path('admin/import-members/', AdminImportMembersView.as_view(), name='admin_import_members'),
    path('activities/', MemberActivityView.as_view(), name='activities'),
    path('admin/activities/', AdminActivityView.as_view(), name='admin_activities'),
    path('admin/activities/<int:pk>/', AdminActivityView.as_view(), name='admin_activity_detail'),
    path('admin/points-settings/', AdminPointsSettingsView.as_view(), name='admin_points_settings'),
    path('leaderboard/', LeaderboardView.as_view(), name='leaderboard'),
    path('news/', NewsListView.as_view(), name='news_list'),
    path('news/<int:post_id>/', NewsDetailView.as_view(), name='news_detail'),
    path('news/create/', NewsCreateView.as_view(), name='news_create'),
    path('news/<int:post_id>/like/', NewsLikeToggleView.as_view(), name='news_like_toggle'),
    path('admin/news/pending/', AdminPendingNewsView.as_view(), name='admin_pending_news'),
    path('admin/news/review/', AdminReviewNewsView.as_view(), name='admin_review_news'),
    path('stats/public/', PublicStatsView.as_view(), name='public_stats'),
    path('events/upcoming/', PublicUpcomingEventsView.as_view(), name='events_upcoming'),
    path('leaderboard/monthly-champions/', MonthlyCategoryChampionsView.as_view(), name='monthly_champions'),
    path('dev-login/', DevLoginView.as_view(), name='dev_login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]
