# Generated by Django 4.2.30 on 2026-06-03 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الفئة')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='رمز الفئة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'فئة',
                'verbose_name_plural': 'الفئات',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_category_manual',
            field=models.BooleanField(default=False, verbose_name='تصنيف يدوي من الأدمن'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=0, verbose_name='النقاط'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='streak',
            field=models.IntegerField(default=0, verbose_name='أيام الاستمرار المتتالية'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_km',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='مجموع الكيلومترات'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='users.category', verbose_name='الفئة'),
        ),
    ]
