# Generated by Django 4.2.30 on 2026-06-03 00:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_populate_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='عدد النقاط')),
                ('transaction_type', models.CharField(choices=[('walk_activity', 'نشاط مشي معتمد'), ('event_attendance', 'حضور فعالية'), ('admin_adjustment', 'تعديل يدوي من الإدارة'), ('coupon_redemption', 'استبدال كوبون خصم')], max_length=30, verbose_name='نوع الحركة')),
                ('description', models.CharField(max_length=255, verbose_name='الوصف/السبب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الحركة')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_transactions', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة الأدمن')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'حركة نقاط',
                'verbose_name_plural': 'سجل حركات النقاط',
            },
        ),
    ]
