# Generated by Django 4.2.30 on 2026-06-03 00:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_pointstransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200, verbose_name='اسم الفعالية بالعربية')),
                ('name_en', models.CharField(max_length=200, verbose_name='اسم الفعالية بالإنجليزية')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='وصف الفعالية بالعربية')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='وصف الفعالية بالإنجليزية')),
                ('points', models.IntegerField(default=0, verbose_name='نقاط الحضور')),
                ('km', models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='مسافة الفعالية (كم)')),
                ('is_active', models.BooleanField(default=True, verbose_name='مفتوحة لتسجيل الحضور')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
            ],
            options={
                'verbose_name': 'فعالية',
                'verbose_name_plural': 'الفعاليات',
            },
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('approved', 'تمت الموافقة'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الحضور')),
                ('registered_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ طلب الحضور')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendances', to=settings.AUTH_USER_MODEL, verbose_name='تمت الموافقة بواسطة')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='users.event', verbose_name='الفعالية')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'حضور فعالية',
                'verbose_name_plural': 'سجل حضور الفعاليات',
                'unique_together': {('user', 'event')},
            },
        ),
    ]
