# Generated by Django 4.2.30 on 2026-06-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_event_event_date_event_event_time_event_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=255, verbose_name='اسم الموقع بالعربية')),
                ('name_en', models.CharField(max_length=255, verbose_name='اسم الموقع بالإنجليزية')),
                ('location_url', models.URLField(verbose_name='رابط الخريطة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'موقع جاهز',
                'verbose_name_plural': 'مواقع الفعاليات الجاهزة',
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='height',
            field=models.FloatField(blank=True, null=True, verbose_name='الطول'),
        ),
    ]
