# Generated by Django 4.2.30 on 2026-06-13 17:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_eventlocation_userprofile_height'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberActivityRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=200, verbose_name='اسم النشاط')),
                ('activity_link', models.URLField(verbose_name='رابط النشاط (سترافا أو غيره)')),
                ('claimed_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='المسافة المقطوعة تقريباً (كم)')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('approved_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='المسافة المعتمدة')),
                ('approved_points', models.IntegerField(blank=True, null=True, verbose_name='النقاط المعتمدة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الرفع')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_activities', to=settings.AUTH_USER_MODEL, verbose_name='بواسطة الإداري')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_requests', to=settings.AUTH_USER_MODEL, verbose_name='العضو')),
            ],
            options={
                'verbose_name': 'طلب نشاط حر',
                'verbose_name_plural': 'طلبات الأنشطة الحرة',
            },
        ),
    ]
