# Generated by Django 4.2.30 on 2026-06-13 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_memberactivityrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('km_points_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=6, verbose_name='نقاط الكيلومتر الواحد (نشاط فردي)')),
                ('monthly_goal_points', models.DecimalField(decimal_places=2, default=200.0, max_digits=6, verbose_name='نقاط تحقيق الهدف الشهري')),
                ('rank_1_points', models.DecimalField(decimal_places=2, default=500.0, max_digits=6, verbose_name='نقاط المركز الأول')),
                ('rank_2_points', models.DecimalField(decimal_places=2, default=300.0, max_digits=6, verbose_name='نقاط المركز الثاني')),
                ('rank_3_points', models.DecimalField(decimal_places=2, default=200.0, max_digits=6, verbose_name='نقاط المركز الثالث')),
                ('most_improved_points', models.DecimalField(decimal_places=2, default=250.0, max_digits=6, verbose_name='نقاط الأكثر تطوراً')),
                ('content_points', models.DecimalField(decimal_places=2, default=30.0, max_digits=6, verbose_name='نقاط المحتوى المعتمد')),
                ('inspiring_story_points', models.DecimalField(decimal_places=2, default=100.0, max_digits=6, verbose_name='نقاط القصة الملهمة')),
                ('streak_7_points', models.DecimalField(decimal_places=2, default=50.0, max_digits=6, verbose_name='نقاط إنجاز استمرارية 7 أيام')),
                ('streak_30_points', models.DecimalField(decimal_places=2, default=200.0, max_digits=6, verbose_name='نقاط إنجاز استمرارية 30 يوم')),
                ('interaction_points', models.DecimalField(decimal_places=2, default=2.0, max_digits=6, verbose_name='نقاط التفاعل')),
                ('interaction_daily_cap', models.IntegerField(default=10, verbose_name='السقف اليومي لنقاط التفاعل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخر تحديث')),
            ],
            options={
                'verbose_name': 'إعدادات النقاط',
                'verbose_name_plural': 'إعدادات النقاط',
            },
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='applied_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='المعدل المطبق وقت المنح'),
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='season_year',
            field=models.IntegerField(default=2026, verbose_name='سنة الاحتساب'),
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='source_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='معرف المصدر'),
        ),
        migrations.AddField(
            model_name='pointstransaction',
            name='source_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='نوع المصدر'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='عدد النقاط'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='transaction_type',
            field=models.CharField(choices=[('walk_activity', 'نشاط مشي معتمد'), ('event_attendance', 'حضور فعالية'), ('event_distance', 'مسافة من فعالية'), ('admin_adjustment', 'تعديل يدوي من الإدارة'), ('coupon_redemption', 'استبدال كوبون خصم'), ('most_improved', 'الأكثر تطوراً'), ('monthly_goal', 'تحقيق هدف الشهر'), ('monthly_rank', 'مركز شهري'), ('content_creation', 'صناعة محتوى'), ('streak_bonus', 'إنجاز استمرارية')], max_length=30, verbose_name='نوع الحركة'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='النقاط'),
        ),
    ]
