# Generated by Django 4.2.30 on 2026-06-13 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_pointssettings_pointstransaction_applied_rate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointssettings',
            name='content_points',
            field=models.IntegerField(default=30, verbose_name='نقاط المحتوى المعتمد'),
        ),
        migrations.AlterField(
            model_name='pointssettings',
            name='inspiring_story_points',
            field=models.IntegerField(default=100, verbose_name='نقاط القصة الملهمة'),
        ),
        migrations.AlterField(
            model_name='pointssettings',
            name='interaction_points',
            field=models.IntegerField(default=2, verbose_name='نقاط التفاعل'),
        ),
        migrations.AlterField(
            model_name='pointssettings',
            name='monthly_goal_points',
            field=models.IntegerField(default=200, verbose_name='نقاط تحقيق الهدف الشهري'),
        ),
        migrations.AlterField(
            model_name='pointssettings',
            name='most_improved_points',
            field=models.IntegerField(default=250, verbose_name='نقاط الأكثر تطوراً'),
        ),
        migrations.AlterField(
            model_name='pointssettings',
            name='rank_1_points',
            field=models.IntegerField(default=500, verbose_name='نقاط المركز الأول'),
        ),
        migrations.AlterField(
            model_name='pointssettings',
            name='rank_2_points',
            field=models.IntegerField(default=300, verbose_name='نقاط المركز الثاني'),
        ),
        migrations.AlterField(
            model_name='pointssettings',
            name='rank_3_points',
            field=models.IntegerField(default=200, verbose_name='نقاط المركز الثالث'),
        ),
        migrations.AlterField(
            model_name='pointssettings',
            name='streak_30_points',
            field=models.IntegerField(default=200, verbose_name='نقاط إنجاز استمرارية 30 يوم'),
        ),
        migrations.AlterField(
            model_name='pointssettings',
            name='streak_7_points',
            field=models.IntegerField(default=50, verbose_name='نقاط إنجاز استمرارية 7 أيام'),
        ),
        migrations.AlterField(
            model_name='pointstransaction',
            name='amount',
            field=models.IntegerField(verbose_name='عدد النقاط'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(default=0, verbose_name='النقاط'),
        ),
    ]
