# Generated by Django 4.2.30 on 2026-06-13 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_pointssettings_content_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pointssettings',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='pointssettings',
            name='content_points',
            field=models.IntegerField(default=20, verbose_name='نقاط المحتوى المعتمد'),
        ),
        migrations.AlterField(
            model_name='pointssettings',
            name='inspiring_story_points',
            field=models.IntegerField(default=50, verbose_name='نقاط القصة الملهمة'),
        ),
        migrations.AlterField(
            model_name='pointssettings',
            name='interaction_daily_cap',
            field=models.IntegerField(default=5, verbose_name='السقف اليومي لنقاط التفاعل'),
        ),
        migrations.AlterField(
            model_name='pointssettings',
            name='interaction_points',
            field=models.IntegerField(default=1, verbose_name='نقاط التفاعل'),
        ),
        migrations.AlterField(
            model_name='pointssettings',
            name='km_points_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=5, verbose_name='نقاط الكيلومتر الواحد'),
        ),
        migrations.AlterField(
            model_name='pointssettings',
            name='monthly_goal_points',
            field=models.IntegerField(default=50, verbose_name='نقاط تحقيق الهدف الشهري'),
        ),
        migrations.AlterField(
            model_name='pointssettings',
            name='most_improved_points',
            field=models.IntegerField(default=30, verbose_name='نقاط الأكثر تطوراً'),
        ),
        migrations.AlterField(
            model_name='pointssettings',
            name='rank_1_points',
            field=models.IntegerField(default=100, verbose_name='نقاط المركز الأول'),
        ),
        migrations.AlterField(
            model_name='pointssettings',
            name='rank_2_points',
            field=models.IntegerField(default=75, verbose_name='نقاط المركز الثاني'),
        ),
        migrations.AlterField(
            model_name='pointssettings',
            name='rank_3_points',
            field=models.IntegerField(default=50, verbose_name='نقاط المركز الثالث'),
        ),
        migrations.AlterField(
            model_name='pointssettings',
            name='streak_30_points',
            field=models.IntegerField(default=50, verbose_name='نقاط استمرارية 30 يوم'),
        ),
        migrations.AlterField(
            model_name='pointssettings',
            name='streak_7_points',
            field=models.IntegerField(default=15, verbose_name='نقاط استمرارية 7 أيام'),
        ),
    ]
