# Generated by Django 4.2.30 on 2026-06-13 18:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_pointssettings_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointssettings',
            name='annual_goal_km',
            field=models.IntegerField(default=100000, verbose_name='الهدف السنوي للفريق (كم)'),
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان الخبر/الإنجاز')),
                ('content', models.TextField(verbose_name='محتوى الخبر')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='الصورة المرفقة')),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة'), ('approved', 'مقبول ونُشر'), ('rejected', 'مرفوض')], default='pending', max_length=20, verbose_name='حالة الخبر')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ النشر')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to=settings.AUTH_USER_MODEL, verbose_name='الناشر')),
            ],
            options={
                'verbose_name': 'خبر / إنجاز',
                'verbose_name_plural': 'الأخبار والإنجازات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='users.newspost')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'إعجاب',
                'verbose_name_plural': 'الإعجابات',
                'unique_together': {('user', 'post')},
            },
        ),
    ]
