# Generated by Django 4.2.30 on 2026-06-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_pointssettings_annual_goal_km_newspost_newslike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberactivityrequest',
            name='activity_link',
            field=models.URLField(unique=True, verbose_name='رابط النشاط (سترافا أو غيره)'),
        ),
    ]
