# Generated by Django 4.2.30 on 2026-06-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_memberactivityrequest_activity_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_reviewer',
            field=models.BooleanField(default=False, verbose_name='مُراجع أنشطة'),
        ),
    ]
