# Generated by Django 4.2.30 on 2026-06-16 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_user_is_reviewer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_content_manager',
            field=models.BooleanField(default=False, verbose_name='مدير المحتوى'),
        ),
    ]
