# Generated by Django 4.2.30 on 2026-06-17 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_memberactivityrequest_activity_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspost',
            name='news_type',
            field=models.CharField(choices=[('member', 'مشاركة عضو'), ('team', 'أخبار الفريق')], default='member', max_length=20, verbose_name='نوع الخبر'),
        ),
    ]
