# Generated by Django 5.2 on 2026-06-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_newspost_news_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointstransaction',
            name='km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='الكيلومترات'),
        ),
    ]
